#+TITLE: Democracies, eh? 
#+AUTHOR: Peixian Wang
#+DATE: 2017-10-07
#+TAGS: :Politics

The New York Times posed an interesting question in their newsletter, /The Interpreter/: https://www.nytimes.com/newsletters/2017/10/06/the-interpreter?nlid=80296480. I was going to write in, but I figured I’d post my answer here first: 

Democracy (at least in the modern sense) evokes an idea of civil liberties, a sense that the government is held accountable to the people, for the people. This exists on a parallel axis to the western world, where most people are for civil liberties, for the basic human rights, for a sense of national unity, leading their governments to reflect on that. 

Daw Aung San Suu Kyi leaves an interesting twist in the idea of democracy. Make no mistake, the slaughter and racial cleansing of the Rohingya Muslims is not only a gross violation of human rights, it is a despicable atrocity. Yet, even as /the Interpreter/ comments, anti-Rohingya sentiment (bolstered by democratically elected leaders and nationalist monks) are still enforcing the will of the people. They represent the views, no matter how horrendous, that the people themselves hold. We cannot say that these governments are illegitimate and must be forcibly removed (although the US certainly attempted that in South America), as they are still democratic nations at their core. 

When does an elected government lose the moral authority to associate with democracy? When the elected government sheds the views of the people. Democracy is not a panacea for human nature, it is a governmental form, some might say a particularly strong one, that attempts to leverage our desire for self-determination into a cohesive strategy for government. There is no need for revolutions when you can simply vote your leaders out. There is no need for violent riots, or for citizens to suffer underneath a democracy. The idea of the democracy is to be held accountable to the people. 

When the people’s views are deplorable, it is those we must understand first. Why does anti-Rohingya sentiment run so deep in Burma? What chain of situations have gotten ourselves here? It it those questions we must answer, while untangling the idea of modern civil liberties from the idea of democracy itself. We should supply aid and peacekeeping forces to Burma to quell this gross violation of human rights, but we must take care to not project the western views of democracy onto other democratic nations. 
