* Great Games, Local Rules
** Setting the Stage
Alexander Cooley’s /Great Games, Local Rules/ is a treasure of a book. It is an information laden trove of knowledge about the Central Asian region, following the collapse of the Soviet Union and the entry of the United States by way of The Global War on terror. Cooley weaves a tapestry of the region only a skilled scholar could, with a novel that slices the region’s interwoven geopolitics apart for the reader to grasp.

Cooley’s thesis is this: following the collapse of the Soviet Union, the retreat of the socialist economy giving way to a market based economy, each of the Central Asian countries (Kazakhstan, Uzbekistan, Kyrgyzstan, Tajikistan, and Turkmenistan) formed a series of unwritten geopolitical local rules, restricting what could be accomplished throughout the region. As the United States barges through the region headfirst as part of the Global War on Terror, Russia is keen to reassert itself as a patron to its former states, yet both face a rising China, whose economy and political situation has approached normalcy. Each of these 3 great powers enters the regions without appropriate knowledge of the local rules, resulting in the locals playing the great powers off of one another for personal gain. 

Cooley takes the reader through each of the great powers and their motivation for such, with Washington needing to secure bases to conduct the Global War on Terror, Moscow wishing to reassert itself in the region and fearful that the regional instability could spread, and China seeing a fresh economy for it to expand into. Each of the great powers have worked together in some form, with joint US-Russia troops, the Shanghai dialog for China-Russia talks; yet it is not the great powers that take the stage on the steppes of Central Asia, it is the local players who are far more interesting. 

** Actors of the of Steppes
Kazakhstan is the largest country in Central Asia, dominating the Russian border and squeezes itself next to China as well. It remains well within the Soviet sphere of influence, 

Uzbekistan - 
Kyrgyzstan - 
Tajikistan - 
Turkministan -

** Wherefore Art Thou, Great Powers? 
During the era of the Soviet Union, Central Asia’s resources were tightly coupled, with shared electrical grids, hydrocarbons directed towards Russia, standardized rail systems, and common trade routes. As the Soviet Union collapsed, each state turned inward, neglecting both the trade routes and the rail systems, leading to a utility system in disrepair. Kyrgyzstan in particular has started to develop its domestic oil reserves, as during the Soviet days Uzbekistan and Kazakhstan sustained the domestic needs. However, as each of the states finds their own feet and joins the global market (Kyrgyzstan in particular is the only one of the Central Asian states in the WTO), each state has less reason for regional dependence, thus reducing the need for a supranational EU-like entity.  
Yet many on the outside naively treat the region as a single, contiguous region, failing to account for the minutiae of local rules. NGO’s (who were viewed with suspicion following the Color Revolutions in the region as Western spies) have long approached the region with a singular, overarching strategy in mind, and have failed to adapt following Moscow’s lead on pushing out NGO’s. 
** Eagles, Dragons, Bear.

*** 
